workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never  # Prevent pipeline run for push event
    - when: always # Run pipeline for all other cases

ios-release:
  stage: build
  tags:
    - macos
  script:
    - export VERSION=$(node -pe "require('./package.json').version")
    - npm install
    - cd ./ios
    - pod install
    - xcodebuild -workspace SoSa.xcworkspace -scheme SoSa clean archive -configuration release -sdk iphoneos -archivePath SoSa.xcarchive -allowProvisioningUpdates
    - xcodebuild -archivePath SoSa.xcarchive -exportPath ./$VERSION -exportOptionsPlist ~/ExportOptions.plist -exportArchive -allowProvisioningUpdates
  artifacts:
    paths:
      - ios/$VERSION/SoSa.ipa

test:
  stage: test
  tags:
    - macos
  script:
    - echo "Future test job"

deploy-ios:
  stage: deploy
  tags:
    - macos
  script:
    - export VERSION=$(node -pe "require('./package.json').version")
    - appcenter distribute release -f ./ios/$VERSION/SoSa.ipa/SoSa.ipa --app $APPCENTER_IOS_APP --group $APPCENTER_DISTRIBUTION
    - echo "Future deploy job"
