workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never  # Prevent pipeline run for push event
    - when: always # Run pipeline for all other cases

ios-release:
  stage: build
  tags:
    - macos
  script:
    - export VERSION=$(node -pe "require('./package.json').version")
    - npm install
    - cd ./ios
    - mkdir -p release/$VERSION
    - pod install
    - xcodebuild -workspace SoSa.xcworkspace -scheme SoSa clean archive -configuration release -sdk iphoneos -archivePath SoSa.xcarchive -allowProvisioningUpdates
    - xcodebuild -archivePath SoSa.xcarchive -exportPath ./release/$VERSION/SoSa.ipa -exportOptionsPlist ~/ExportOptions.plist -exportArchive -allowProvisioningUpdates
  artifacts:
    paths:
      - ios/release/$VERSION/*

test:
  stage: test
  tags:
    - macos
  script:
    - echo "Future test job"

deploy:
  stage: deploy
  tags:
    - macos
  script:
    - export VERSION=$(node -pe "require('./package.json').version")
    - echo "Future deploy job"
