workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never  # Prevent pipeline run for push event
    - when: always # Run pipeline for all other cases

ios-release:
  stage: build
  tags:
    - macos
  script:
    - npm install
    - cd ./ios
    - mkdir release
    - ls -l ~/
    - pod install
    - xcodebuild -workspace SoSa.xcworkspace -scheme SoSa clean archive -configuration release -sdk iphoneos -archivePath SoSa.xcarchive -allowProvisioningUpdates
    - xcodebuild -archivePath SoSa.xcarchive -exportPath ./release/SoSa.ipa -exportOptionsPlist ~/ExportOptions.plist -exportArchive
  artifacts:
    paths:
      - ios/release

test:
  stage: test
  tags:
    - macos
  script:
    - echo "Future test job"

deploy:
  stage: deploy
  tags:
    - macos
  script:
    - echo "Future deploy job"
