workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never  # Prevent pipeline run for push event
    - when: always # Run pipeline for all other cases

ios-release:
  stage: build
  tags:
    - macos
  script:
    - export VERSION=$(node -pe "require('./package.json').version")
    - npm install
    - cd ./ios
    - pod install
    - mkdir release
    - xcodebuild -workspace SoSa.xcworkspace -scheme SoSa clean archive -configuration release -sdk iphoneos -archivePath SoSa.xcarchive -allowProvisioningUpdates
    - xcodebuild -archivePath SoSa.xcarchive -exportPath ./release -exportOptionsPlist ~/ExportOptions.plist -exportArchive -allowProvisioningUpdates
    - ls -l ./release/
  artifacts:
    paths:
      - ios/release/

test:
  stage: test
  tags:
    - macos
  script:
    - echo "Future test job"

deploy-ios:
  stage: deploy
  tags:
    - macos
  script:
    - export VERSION=$(node -pe "require('./package.json').version")
    - ls -l ./ios/release/
    - appcenter distribute release -f ./ios/release/SoSa.ipa --app $APPCENTER_IOS_APP --group $APPCENTER_DISTRIBUTION
    - mkdir -p ~/release/ios/$VERSION
    - cp -R ./ios/release/* ~/release/ios/$VERSION/
    - echo "Future deploy job"
