build-job:
  stage: build
  tags:
    - macos
  script:
    - npm install
    - cd ./android
    - ./gradlew assemble
  artifacts:
    paths:
      - app/build/outputs/apk/debug

test-job1:
  stage: test
  tags:
    - macos
  script:
    - echo "This job tests something"

test-job2:
  stage: test
  tags:
    - macos
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - sleep 20

deploy-prod:
  stage: deploy
  tags:
    - macos
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."