require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '10.0'

target 'SoSa' do
  # Pods for SoSa
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'SoSaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable these next few lines.
    #use_flipper!
    post_install do |installer|
      #flipper_post_install(installer)
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
            if Gem::Version.new('10.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
            end
          end
      end
    end
end

target 'SoSa-tvOS' do
  # Pods for SoSa-tvOS

  target 'SoSa-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
